#############################################################################
# Makefile for building: MyConcurrentModel.app/Contents/MacOS/MyConcurrentModel
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  MyConcurrentModel.pro
# Template: app
# Command: /Applications/Qt/5.5/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile MyConcurrentModel.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -Imodellib -I../5.5/clang_64/lib/QtWidgets.framework/Headers -I../5.5/clang_64/lib/QtGui.framework/Headers -I../5.5/clang_64/lib/QtConcurrent.framework/Headers -I../5.5/clang_64/lib/QtCore.framework/Headers -I. -I../../Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I../../Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../5.5/clang_64/mkspecs/macx-clang -F/Applications/Qt/5.5/clang_64/lib
QMAKE         = /Applications/Qt/5.5/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = MyConcurrentModel1.0.0
DISTDIR = /Applications/Qt/MyConcurrentModel/.tmp/MyConcurrentModel1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -stdlib=libc++ -mmacosx-version-min=10.7 -Wl,-rpath,/Applications/Qt/5.5/clang_64/lib
LIBS          = $(SUBLIBS) -F/Applications/Qt/5.5/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtConcurrent -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		dialog.cpp \
		modellib/cell.cpp \
		modellib/kurata08.cpp \
		modellib/proto.cpp \
		myoutput.cpp moc_dialog.cpp \
		moc_myoutput.cpp
OBJECTS       = main.o \
		dialog.o \
		cell.o \
		kurata08.o \
		proto.o \
		myoutput.o \
		moc_dialog.o \
		moc_myoutput.o
DIST          = ../5.5/clang_64/mkspecs/features/spec_pre.prf \
		../5.5/clang_64/mkspecs/qdevice.pri \
		../5.5/clang_64/mkspecs/features/device_config.prf \
		../5.5/clang_64/mkspecs/common/unix.conf \
		../5.5/clang_64/mkspecs/common/mac.conf \
		../5.5/clang_64/mkspecs/common/macx.conf \
		../5.5/clang_64/mkspecs/common/sanitize.conf \
		../5.5/clang_64/mkspecs/common/gcc-base.conf \
		../5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../5.5/clang_64/mkspecs/common/clang.conf \
		../5.5/clang_64/mkspecs/common/clang-mac.conf \
		../5.5/clang_64/mkspecs/qconfig.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../5.5/clang_64/mkspecs/features/qt_functions.prf \
		../5.5/clang_64/mkspecs/features/qt_config.prf \
		../5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../5.5/clang_64/mkspecs/features/spec_post.prf \
		../5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../5.5/clang_64/mkspecs/features/default_pre.prf \
		../5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../5.5/clang_64/mkspecs/features/resolve_config.prf \
		../5.5/clang_64/mkspecs/features/default_post.prf \
		../5.5/clang_64/mkspecs/features/c++11.prf \
		../5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../5.5/clang_64/mkspecs/features/warn_on.prf \
		../5.5/clang_64/mkspecs/features/qt.prf \
		../5.5/clang_64/mkspecs/features/resources.prf \
		../5.5/clang_64/mkspecs/features/moc.prf \
		../5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../5.5/clang_64/mkspecs/features/uic.prf \
		../5.5/clang_64/mkspecs/features/unix/thread.prf \
		../5.5/clang_64/mkspecs/features/mac/rez.prf \
		../5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../5.5/clang_64/mkspecs/features/exceptions.prf \
		../5.5/clang_64/mkspecs/features/yacc.prf \
		../5.5/clang_64/mkspecs/features/lex.prf \
		MyConcurrentModel.pro dialog.h \
		modellib/cell.h \
		modellib/kurata08.h \
		modellib/proto.h \
		myoutput.h main.cpp \
		dialog.cpp \
		modellib/cell.cpp \
		modellib/kurata08.cpp \
		modellib/proto.cpp \
		myoutput.cpp
QMAKE_TARGET  = MyConcurrentModel
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = MyConcurrentModel.app/Contents/MacOS/MyConcurrentModel

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk \
		-std=c++11 \
		-stdlib=libc++ \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_dialog.h $(OBJECTS)  
	@test -d MyConcurrentModel.app/Contents/MacOS/ || mkdir -p MyConcurrentModel.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MyConcurrentModel.pro ../5.5/clang_64/mkspecs/macx-clang/qmake.conf ../5.5/clang_64/mkspecs/features/spec_pre.prf \
		../5.5/clang_64/mkspecs/qdevice.pri \
		../5.5/clang_64/mkspecs/features/device_config.prf \
		../5.5/clang_64/mkspecs/common/unix.conf \
		../5.5/clang_64/mkspecs/common/mac.conf \
		../5.5/clang_64/mkspecs/common/macx.conf \
		../5.5/clang_64/mkspecs/common/sanitize.conf \
		../5.5/clang_64/mkspecs/common/gcc-base.conf \
		../5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../5.5/clang_64/mkspecs/common/clang.conf \
		../5.5/clang_64/mkspecs/common/clang-mac.conf \
		../5.5/clang_64/mkspecs/qconfig.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../5.5/clang_64/mkspecs/features/qt_functions.prf \
		../5.5/clang_64/mkspecs/features/qt_config.prf \
		../5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../5.5/clang_64/mkspecs/features/spec_post.prf \
		../5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../5.5/clang_64/mkspecs/features/default_pre.prf \
		../5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../5.5/clang_64/mkspecs/features/resolve_config.prf \
		../5.5/clang_64/mkspecs/features/default_post.prf \
		../5.5/clang_64/mkspecs/features/c++11.prf \
		../5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../5.5/clang_64/mkspecs/features/warn_on.prf \
		../5.5/clang_64/mkspecs/features/qt.prf \
		../5.5/clang_64/mkspecs/features/resources.prf \
		../5.5/clang_64/mkspecs/features/moc.prf \
		../5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../5.5/clang_64/mkspecs/features/uic.prf \
		../5.5/clang_64/mkspecs/features/unix/thread.prf \
		../5.5/clang_64/mkspecs/features/mac/rez.prf \
		../5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../5.5/clang_64/mkspecs/features/exceptions.prf \
		../5.5/clang_64/mkspecs/features/yacc.prf \
		../5.5/clang_64/mkspecs/features/lex.prf \
		MyConcurrentModel.pro \
		/Applications/Qt/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Applications/Qt/5.5/clang_64/lib/QtGui.framework/QtGui.prl \
		/Applications/Qt/5.5/clang_64/lib/QtConcurrent.framework/QtConcurrent.prl \
		/Applications/Qt/5.5/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile MyConcurrentModel.pro
../5.5/clang_64/mkspecs/features/spec_pre.prf:
../5.5/clang_64/mkspecs/qdevice.pri:
../5.5/clang_64/mkspecs/features/device_config.prf:
../5.5/clang_64/mkspecs/common/unix.conf:
../5.5/clang_64/mkspecs/common/mac.conf:
../5.5/clang_64/mkspecs/common/macx.conf:
../5.5/clang_64/mkspecs/common/sanitize.conf:
../5.5/clang_64/mkspecs/common/gcc-base.conf:
../5.5/clang_64/mkspecs/common/gcc-base-mac.conf:
../5.5/clang_64/mkspecs/common/clang.conf:
../5.5/clang_64/mkspecs/common/clang-mac.conf:
../5.5/clang_64/mkspecs/qconfig.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_core.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_designer.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_gui.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_help.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_location.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_network.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_qml.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_quick.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_script.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_sql.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_svg.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_xml.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../5.5/clang_64/mkspecs/features/qt_functions.prf:
../5.5/clang_64/mkspecs/features/qt_config.prf:
../5.5/clang_64/mkspecs/macx-clang/qmake.conf:
../5.5/clang_64/mkspecs/features/spec_post.prf:
../5.5/clang_64/mkspecs/features/exclusive_builds.prf:
../5.5/clang_64/mkspecs/features/default_pre.prf:
../5.5/clang_64/mkspecs/features/mac/default_pre.prf:
../5.5/clang_64/mkspecs/features/resolve_config.prf:
../5.5/clang_64/mkspecs/features/default_post.prf:
../5.5/clang_64/mkspecs/features/c++11.prf:
../5.5/clang_64/mkspecs/features/mac/sdk.prf:
../5.5/clang_64/mkspecs/features/mac/default_post.prf:
../5.5/clang_64/mkspecs/features/mac/objective_c.prf:
../5.5/clang_64/mkspecs/features/warn_on.prf:
../5.5/clang_64/mkspecs/features/qt.prf:
../5.5/clang_64/mkspecs/features/resources.prf:
../5.5/clang_64/mkspecs/features/moc.prf:
../5.5/clang_64/mkspecs/features/unix/opengl.prf:
../5.5/clang_64/mkspecs/features/uic.prf:
../5.5/clang_64/mkspecs/features/unix/thread.prf:
../5.5/clang_64/mkspecs/features/mac/rez.prf:
../5.5/clang_64/mkspecs/features/testcase_targets.prf:
../5.5/clang_64/mkspecs/features/exceptions.prf:
../5.5/clang_64/mkspecs/features/yacc.prf:
../5.5/clang_64/mkspecs/features/lex.prf:
MyConcurrentModel.pro:
/Applications/Qt/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Applications/Qt/5.5/clang_64/lib/QtGui.framework/QtGui.prl:
/Applications/Qt/5.5/clang_64/lib/QtConcurrent.framework/QtConcurrent.prl:
/Applications/Qt/5.5/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile MyConcurrentModel.pro

qmake_all: FORCE

MyConcurrentModel.app/Contents/PkgInfo: 
	@test -d MyConcurrentModel.app/Contents || mkdir -p MyConcurrentModel.app/Contents
	@$(DEL_FILE) MyConcurrentModel.app/Contents/PkgInfo
	@echo "APPL????" > MyConcurrentModel.app/Contents/PkgInfo
MyConcurrentModel.app/Contents/Resources/empty.lproj: 
	@test -d MyConcurrentModel.app/Contents/Resources || mkdir -p MyConcurrentModel.app/Contents/Resources
	@touch MyConcurrentModel.app/Contents/Resources/empty.lproj
	
MyConcurrentModel.app/Contents/Info.plist: 
	@test -d MyConcurrentModel.app/Contents || mkdir -p MyConcurrentModel.app/Contents
	@$(DEL_FILE) MyConcurrentModel.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.MyConcurrentModel,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,MyConcurrentModel,g" -e "s,@TYPEINFO@,????,g" ../5.5/clang_64/mkspecs/macx-clang/Info.plist.app >MyConcurrentModel.app/Contents/Info.plist

all: Makefile \
		MyConcurrentModel.app/Contents/PkgInfo \
		MyConcurrentModel.app/Contents/Resources/empty.lproj \
		MyConcurrentModel.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents dialog.h modellib/cell.h modellib/kurata08.h modellib/proto.h myoutput.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp dialog.cpp modellib/cell.cpp modellib/kurata08.cpp modellib/proto.cpp myoutput.cpp $(DISTDIR)/
	$(COPY_FILE) --parents dialog.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r MyConcurrentModel.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_dialog.cpp moc_myoutput.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dialog.cpp moc_myoutput.cpp
moc_dialog.cpp: ../5.5/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../5.5/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../5.5/clang_64/lib/QtWidgets.framework/Headers/QProgressDialog \
		../5.5/clang_64/lib/QtWidgets.framework/Headers/qprogressdialog.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/QtConcurrent \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentcompilertest.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentexception.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfilter.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfilterkernel.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfunctionwrappers.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentiteratekernel.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmap.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmapkernel.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmedian.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentreducekernel.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentrun.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentrunbase.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentstoredfunctioncall.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentthreadengine.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentversion.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QThread \
		../5.5/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QFutureWatcher \
		../5.5/clang_64/lib/QtCore.framework/Headers/qfuturewatcher.h \
		../5.5/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../5.5/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QPointer \
		../5.5/clang_64/lib/QtCore.framework/Headers/qpointer.h \
		modellib/proto.h \
		modellib/kurata08.h \
		modellib/cell.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		dialog.h
	/Applications/Qt/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Applications/Qt/5.5/clang_64/mkspecs/macx-clang -I/Applications/Qt/MyConcurrentModel -I/Applications/Qt/MyConcurrentModel/modellib -I/Applications/Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.5/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.5/clang_64/lib/QtConcurrent.framework/Headers -I/Applications/Qt/5.5/clang_64/lib/QtCore.framework/Headers -F/Applications/Qt/5.5/clang_64/lib dialog.h -o moc_dialog.cpp

moc_myoutput.cpp: ../5.5/clang_64/lib/QtCore.framework/Headers/QObject \
		../5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QFile \
		../5.5/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QFileInfo \
		../5.5/clang_64/lib/QtCore.framework/Headers/qfileinfo.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../5.5/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		myoutput.h
	/Applications/Qt/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Applications/Qt/5.5/clang_64/mkspecs/macx-clang -I/Applications/Qt/MyConcurrentModel -I/Applications/Qt/MyConcurrentModel/modellib -I/Applications/Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.5/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.5/clang_64/lib/QtConcurrent.framework/Headers -I/Applications/Qt/5.5/clang_64/lib/QtCore.framework/Headers -F/Applications/Qt/5.5/clang_64/lib myoutput.h -o moc_myoutput.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_dialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_dialog.h
ui_dialog.h: dialog.ui
	/Applications/Qt/5.5/clang_64/bin/uic dialog.ui -o ui_dialog.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp dialog.h \
		../5.5/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../5.5/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../5.5/clang_64/lib/QtWidgets.framework/Headers/QProgressDialog \
		../5.5/clang_64/lib/QtWidgets.framework/Headers/qprogressdialog.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/QtConcurrent \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentcompilertest.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentexception.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfilter.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfilterkernel.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfunctionwrappers.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentiteratekernel.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmap.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmapkernel.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmedian.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentreducekernel.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentrun.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentrunbase.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentstoredfunctioncall.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentthreadengine.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentversion.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QThread \
		../5.5/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QFutureWatcher \
		../5.5/clang_64/lib/QtCore.framework/Headers/qfuturewatcher.h \
		../5.5/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../5.5/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QPointer \
		../5.5/clang_64/lib/QtCore.framework/Headers/qpointer.h \
		modellib/proto.h \
		modellib/kurata08.h \
		modellib/cell.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../5.5/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../5.5/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

dialog.o: dialog.cpp dialog.h \
		../5.5/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../5.5/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../5.5/clang_64/lib/QtWidgets.framework/Headers/QProgressDialog \
		../5.5/clang_64/lib/QtWidgets.framework/Headers/qprogressdialog.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/QtConcurrent \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentcompilertest.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentexception.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfilter.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfilterkernel.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentfunctionwrappers.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentiteratekernel.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmap.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmapkernel.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentmedian.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentreducekernel.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentrun.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentrunbase.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentstoredfunctioncall.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentthreadengine.h \
		../5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentversion.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QThread \
		../5.5/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QFutureWatcher \
		../5.5/clang_64/lib/QtCore.framework/Headers/qfuturewatcher.h \
		../5.5/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../5.5/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QPointer \
		../5.5/clang_64/lib/QtCore.framework/Headers/qpointer.h \
		modellib/proto.h \
		modellib/kurata08.h \
		modellib/cell.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		ui_dialog.h \
		myoutput.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QObject \
		../5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QFile \
		../5.5/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QFileInfo \
		../5.5/clang_64/lib/QtCore.framework/Headers/qfileinfo.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../5.5/clang_64/lib/QtCore.framework/Headers/qtextstream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

cell.o: modellib/cell.cpp modellib/cell.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../5.5/clang_64/lib/QtCore.framework/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cell.o modellib/cell.cpp

kurata08.o: modellib/kurata08.cpp modellib/kurata08.h \
		modellib/cell.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../5.5/clang_64/lib/QtCore.framework/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kurata08.o modellib/kurata08.cpp

proto.o: modellib/proto.cpp modellib/proto.h \
		modellib/kurata08.h \
		modellib/cell.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o proto.o modellib/proto.cpp

myoutput.o: myoutput.cpp myoutput.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QObject \
		../5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QFile \
		../5.5/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QFileInfo \
		../5.5/clang_64/lib/QtCore.framework/Headers/qfileinfo.h \
		../5.5/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../5.5/clang_64/lib/QtCore.framework/Headers/qtextstream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myoutput.o myoutput.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

moc_myoutput.o: moc_myoutput.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myoutput.o moc_myoutput.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

